# 2 预备知识

## 2.1 数据操作

#### 创建与基础属性

In [80]:
import torch    #导入torch库

In [81]:
#torch.arange(start=0, end, step=1),优先按照end参数生成一个行向量
x = torch.arange(12)    #创建行向量
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [82]:
x.shape #访问张量的形状

torch.Size([12])

In [83]:
x.numel()  #访问张量的元素数量

12

In [84]:
y = torch.reshape(x,(2,6))  #将张量x的形状变为2行6列
print(x)
print(y)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


In [85]:
x = x.reshape(3,4)  #可以用x.reshape(-1,4)或x.reshape(3,-1)来取代x.reshape(3,4)
print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [86]:
torch.zeros((2,3,4))    #全0初始化
torch.ones((2,3,4))     #全1初始化
torch.randn((2,3,4))    #标准正态分布初始化

tensor([[[ 0.3211, -1.3241,  0.4220, -1.1822],
         [ 1.3449, -0.3656,  0.5422, -1.0907],
         [ 0.5124, -1.8186, -0.6617,  0.2576]],

        [[ 1.2047,  2.6725,  1.2790, -0.0733],
         [ 0.1808, -2.4886, -0.3623,  0.9320],
         [-1.0295, -0.8470,  0.0912, -1.0383]]])

In [87]:
torch.tensor([[1,2,3],[4,5,6]])  #通过嵌套列表创建张量

tensor([[1, 2, 3],
        [4, 5, 6]])

#### 运算符

In [88]:
x = torch.tensor([1.0 , 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])


In [89]:
x + y, x - y, x * y, x / y, x ** y  #张量的幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [90]:
torch.exp(x)    #张量的指数运算

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [91]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))    
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)  #按行和按列连接张量
#行（轴‐0，形状的第一个元素）和按列（轴‐1，形状的第二个元素）

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [92]:
X == Y  #张量的比较运算

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [93]:
#练习
print(X < Y)
print(X > Y)

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])


In [94]:
X.sum() #张量元素的和

tensor(66.)

#### 广播机制

相同形状的两个张量可以执行按元素操作。对于 **不同形状的张量** ，可以通过 **广播机制（broadcasting mechanism）** 执行按元素操作。

工作机制如下：
1. 通过适当复制元素来拓展一个或两个数组，以便在转换之后，两个张量具有相同的形状；
2. 对生成的数组执行按元素操作。

在大多数情况下，我们将沿着数组中长度为1的轴进行广播。

In [95]:
a = torch.arange(3).reshape((3, 1)) 
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [96]:
a+b  #广播机制，矩阵a将复制列，矩阵b将复制行，然后再按元素相加

tensor([[0, 1],
        [1, 2],
        [2, 3]])

#### 索引和切片

In [97]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [98]:
X[-1],X[1,2],X[1:3]    #张量的索引和切片  

(tensor([ 8.,  9., 10., 11.]),
 tensor(6.),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [99]:
X[2, 0] = 9     #修改张量元素
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 9.,  9., 10., 11.]])

#### 节省内存

In [100]:
before = id(Y)
Y = Y + X
id(Y) == before #张量Y的内存地址发生变化

False

说明一些操作会为其结果分配新内存。可以使用 **切片表示法** 将操作的结果分配给先前分配的数组，以实现 **原地操作**。

In [101]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 2702294384016
id(Z): 2702294384016


#### 转换为其他Python对象

In [102]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)    #torch张量和numpy数组将共享它们的底层内存，就地操作更改一个张量也会同时更改另一个张量

(numpy.ndarray, torch.Tensor)

In [103]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)   #将大小为1的张量转换为Python标量

(tensor([3.5000]), 3.5, 3.5, 3)

---

##### **练习**

1. 会得到相应各位置比较后的bool类型的输出
2. 如下：同样地按一维进行广播

In [104]:
x = torch.tensor([[[1,2],[3,4]]])  #3维张量，1维1个，2维2个，3维2个
print(x.shape)  #访问张量的形状
y = torch.tensor([[[5,6]],[[7,8]]]) #3维张量，1维2个，2维1个，3维2个
print(y.shape)
x + y, x == y
#[[[1,2],[3,4]][[1,2],[3,4]]] + [[[5,6],[5,6]],[[7,8],[7,8]]]

torch.Size([1, 2, 2])
torch.Size([2, 1, 2])


(tensor([[[ 6,  8],
          [ 8, 10]],
 
         [[ 8, 10],
          [10, 12]]]),
 tensor([[[False, False],
          [False, False]],
 
         [[False, False],
          [False, False]]]))

---

## 2.2 数据预处理

使用 **pandas** 包预处理原始数据，并将原始数据转换为张量格式。

#### 读取

In [105]:
import os   
#os库提供了一系列与操作系统交互的函数，用于管理文件系统、进程、环境变量等系统级操作

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
# os.makedirs()函数用于创建多级目录，exist_ok=True表示如果目录已存在则不报错

data_file = os.path.join('..', 'data', 'house_tiny.csv')
# os.path.join()函数用于将多个路径组件连接成一个完整的路径
# '..'表示上一级目录，'data'是新建的目录名，'house_tiny.csv'是数据文件名
# 这里创建一个CSV文件，包含一些房屋数据

with open(data_file, 'w') as f:
# open()函数用于打开文件，'w'表示以写入模式打开文件

    f.write('NumRooms,Alley,Price\n') # 列名
    f.write('NA,Pave,127500\n') # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

| **排名** | **操作**               | **代码示例**                          | **用途**                              |
|----------|-------------------------|---------------------------------------|---------------------------------------|
| 1        | **路径拼接**           | `os.path.join("dir", "file.txt")`    | 跨平台安全拼接路径（自动处理`/`或`\`）|
| 2        | **检查文件/目录存在**  | `os.path.exists("data.txt")`         | 避免操作不存在的路径                  |
| 3        | **列出目录内容**       | `os.listdir(".")`                    | 获取当前目录下的文件和子目录名        |
| 4        | **获取当前工作目录**   | `os.getcwd()`                        | 调试时确认脚本所在位置                |
| 5        | **创建目录**           | `os.mkdir("new_folder")`             | 快速新建单层目录                      |
| 6        | **删除文件**           | `os.remove("temp.txt")`              | 清理临时文件                          |
| 7        | **重命名/移动文件**    | `os.rename("old.txt", "new.txt")`    | 批量重命名或移动文件位置              |
| 8        | **判断是否为文件**     | `os.path.isfile("file.txt")`         | 确认路径指向文件（非目录）            |
| 9        | **获取文件名/目录名**  | `os.path.basename("/tmp/a.txt")`     | 提取路径中的文件名部分 → `"a.txt"`   |
| 10       | **修改工作目录**       | `os.chdir("../data")`                | 切换脚本操作的根目录                  |

In [106]:
import pandas as pd

data = pd.read_csv(data_file)
# 使用pandas读取CSV文件
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


#### 处理缺失值

在pandas中，NaN项代表缺失值。

为了处理缺失的数据，典型的方法包括 **插值法** 和 **删除法**：
- 插值法：用一个替代值弥补缺失值
- 删除法：直接忽略缺失值

插值法：

In [107]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
# 分离输入特征和输出标签， iloc用于基于位置选择数据

# inputs = inputs.fillna(inputs.mean())将会报错（报错信息如下）
# mean()函数计算每列的均值，fillna()函数将缺失值替换为均值

inputs = inputs.fillna(inputs.select_dtypes(include='number').mean())
# 这里使用select_dtypes(include='number')选择数值类型的列来计算均值，避免非数值列导致的错误
print(inputs)

inputs = pd.get_dummies(inputs, dummy_na=True)
# get_dummies()函数将分类变量转换为独热编码，dummy_na=True表示将缺失值也作为一个类别处理
# 独热编码会为每个类别创建一个新的二进制列
print(inputs)
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN
   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True
   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True


<font color=red>
问题：

1. 执行inputs = inputs.fillna(inputs.mean())：


2. 执行pd.get_dummies(inputs, dummy_na=True)后Alley_Pave与Alley_nan都为bool类型。
解决：默认为uint8类型，应该显示0和1，但是在某些环境（如 Jupyter Notebook）中，Pandas 可能默认用 True/False 显示 bool 列，但实际上存储的值仍是 0 和 1。

#### 向张量转化

In [108]:
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(outputs.to_numpy(dtype=float))
# to_numpy()方法将DataFrame转换为NumPy数组，dtype=float指定数据类型为浮点数
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

## 2.3 线性代数

由于具有“线性代数”和“面向人工智能的线性代数”课程的知识，仅做补充：

- 向量或轴的维度被用来表示向量或轴的长度，即向量或轴的元素数量。张量的某个轴的维数就是这个轴的长度。
- 访问张量的转置可以使用 ``.T()`` 方法。
- 复制（为复制变量赋值新内存）可以使用 ``.clone()`` 方法。


In [109]:
A = torch.arange(20).reshape(5, 4)
B = A.clone()
A, A.T, B, id(A), id(B)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  4,  8, 12, 16],
         [ 1,  5,  9, 13, 17],
         [ 2,  6, 10, 14, 18],
         [ 3,  7, 11, 15, 19]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 2702293989440,
 2702294703296)

- 两个矩阵的按元素乘法称为Hadamard积（Hadamard product）（数学符号⊙）
- 将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘。
- 使用 ``.sum()`` 可以表示任意形状张量的元素和。

In [110]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190))

- 在 ``.sum()`` 中指定 ``axis`` 沿某一维度降维以生成输出向量，该维度消失。 **每一个[]对之间是一个维度的元素**。类似地， ``.mean()`` 也可以通过指定 ``axis`` 求某一维度的平均值。

In [111]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6, 22, 38, 54, 70]), torch.Size([5]))

- 若需要保持轴数不变，需在函数中额外给定 ``keepdims=true`` 。

In [112]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 6],
        [22],
        [38],
        [54],
        [70]])

- 如果我们想沿某个轴计算A元素的累积总和，比如 ``axis=0`` （按行计算），可以调用 ``.cumsum()`` 函数。此函数不会沿任何轴降低输入张量的维度。

In [113]:
A.cumsum(axis=0)

tensor([[ 0,  1,  2,  3],
        [ 4,  6,  8, 10],
        [12, 15, 18, 21],
        [24, 28, 32, 36],
        [40, 45, 50, 55]])

- 向量的点积使用 ``torch.dot(x, y)`` 执行，效果同 ``torch.sum(x * y)``。
- 矩阵-向量积使用 ``torch.mv(A, x)`` 执行。
- 矩阵-矩阵积使用 ``torch.mm(A, B)`` 执行，即矩阵乘法。
- 使用 ``torch.norm(x)`` 计算 *$L_2$* 范数。

---

##### **练习**

4. 如下，返回的是张量 X 的 第一个维度（最外层维度）的大小。
5. 产生The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1的报错。
7. 对 ``.norm`` 输入多轴，默认行为是对所有元素计算范数。

In [114]:
X = torch.arange(24).reshape(2,3,4)
X, len(X)

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 2)